In [2]:
import numpy as np
A = np.array([
    [ 0.0,  2.0, -1.0,  3.0,  6.0],
    [-2.0,  4.0,  1.0, -1.0, -1.0],
    [ 4.0, -2.0,  2.0,  3.0, -3.0],
    [ 2.0,  6.0,  0.0,  2.0,  8.0]
], dtype=float)

In [3]:
def swap_rows(A, i, j):
    temp = A[i].copy()
    A[i] = A[j]
    A[j] = temp

In [4]:
def multiply_row(A, i, k):
    A[i] = A[i] * k

In [5]:
def add_row_multiple(A, dest_row, src_row, k):
    A[dest_row] = A[dest_row] - k*A[src_row]

In [6]:
def is_zero(val, tol=1e-9):
    return abs(val) < tol

In [7]:
def gauss_elimination(A):
    cur_row = 0
    n, m = A.shape
    for j in range (0, m-1):
        if cur_row >= n:
            break

        max_val = 0 
        pivot_row = cur_row
        for i in range (cur_row, n):
            if abs(A[i, j]) > max_val:
                max_val = abs(A[i, j])
                pivot_row = i
        
        if is_zero(max_val):
            continue
        
        swap_rows(A, cur_row, pivot_row)
        
        multiply_row(A, cur_row, 1/A[cur_row, j])

        for k in range (cur_row+1, n):
            val = A[k ,j]
            add_row_multiple(A, k, cur_row, val)

        cur_row += 1

    return A

In [8]:
print("--- MA TRẬN BAN ĐẦU ---")
print(A)
print("\n-----------------------")

# 2. Gọi hàm Gauss để biến đổi ma trận A
A_bac_thang = gauss_elimination(A)

print("--- MA TRẬN BẬC THANG THU ĐƯỢC ---")
print(A_bac_thang)

--- MA TRẬN BAN ĐẦU ---
[[ 0.  2. -1.  3.  6.]
 [-2.  4.  1. -1. -1.]
 [ 4. -2.  2.  3. -3.]
 [ 2.  6.  0.  2.  8.]]

-----------------------
--- MA TRẬN BẬC THANG THU ĐƯỢC ---
[[ 1.         -0.5         0.5         0.75       -0.75      ]
 [ 0.          1.         -0.14285714  0.07142857  1.35714286]
 [ 0.          0.          1.          0.11764706 -2.70588235]
 [ 0.          0.          0.          1.          0.46      ]]
